//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientes_wfc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_DepartmentList_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_DepartmentList_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_DepartmentSave_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_DepartmentSave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_CreditCardList_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_CreditCardList_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditCardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ExpMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExpYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditCardID {
            get {
                return this.CreditCardIDField;
            }
            set {
                if ((this.CreditCardIDField.Equals(value) != true)) {
                    this.CreditCardIDField = value;
                    this.RaisePropertyChanged("CreditCardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ExpMonth {
            get {
                return this.ExpMonthField;
            }
            set {
                if ((this.ExpMonthField.Equals(value) != true)) {
                    this.ExpMonthField = value;
                    this.RaisePropertyChanged("ExpMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExpYear {
            get {
                return this.ExpYearField;
            }
            set {
                if ((this.ExpYearField.Equals(value) != true)) {
                    this.ExpYearField = value;
                    this.RaisePropertyChanged("ExpYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_CreditCardSave_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_CreditCardSave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_ProductCategoryList_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_ProductCategoryList_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID {
            get {
                return this.ProductCategoryIDField;
            }
            set {
                if ((this.ProductCategoryIDField.Equals(value) != true)) {
                    this.ProductCategoryIDField = value;
                    this.RaisePropertyChanged("ProductCategoryID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="stpr_ProductCategorySave_Result", Namespace="http://schemas.datacontract.org/2004/07/adventureworks2019_wcf")]
    [System.SerializableAttribute()]
    public partial class stpr_ProductCategorySave_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentLista", ReplyAction="http://tempuri.org/IService1/DepartmentListaResponse")]
        clientes_wfc.ServiceReference1.stpr_DepartmentList_Result[] DepartmentLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentLista", ReplyAction="http://tempuri.org/IService1/DepartmentListaResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentList_Result[]> DepartmentListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentDatos", ReplyAction="http://tempuri.org/IService1/DepartmentDatosResponse")]
        clientes_wfc.ServiceReference1.stpr_DepartmentList_Result DepartmentDatos(int DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentDatos", ReplyAction="http://tempuri.org/IService1/DepartmentDatosResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentList_Result> DepartmentDatosAsync(int DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentSave", ReplyAction="http://tempuri.org/IService1/DepartmentSaveResponse")]
        clientes_wfc.ServiceReference1.stpr_DepartmentSave_Result DepartmentSave(int DepartmentID, string Name, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DepartmentSave", ReplyAction="http://tempuri.org/IService1/DepartmentSaveResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentSave_Result> DepartmentSaveAsync(int DepartmentID, string Name, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardLista", ReplyAction="http://tempuri.org/IService1/CreditCardListaResponse")]
        clientes_wfc.ServiceReference1.stpr_CreditCardList_Result[] CreditCardLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardLista", ReplyAction="http://tempuri.org/IService1/CreditCardListaResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardList_Result[]> CreditCardListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardDatos", ReplyAction="http://tempuri.org/IService1/CreditCardDatosResponse")]
        clientes_wfc.ServiceReference1.stpr_CreditCardList_Result CreditCardDatos(int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardDatos", ReplyAction="http://tempuri.org/IService1/CreditCardDatosResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardList_Result> CreditCardDatosAsync(int creditCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardSave", ReplyAction="http://tempuri.org/IService1/CreditCardSaveResponse")]
        clientes_wfc.ServiceReference1.stpr_CreditCardSave_Result CreditCardSave(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreditCardSave", ReplyAction="http://tempuri.org/IService1/CreditCardSaveResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardSave_Result> CreditCardSaveAsync(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategoryLista", ReplyAction="http://tempuri.org/IService1/ProductCategoryListaResponse")]
        clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result[] ProductCategoryLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategoryLista", ReplyAction="http://tempuri.org/IService1/ProductCategoryListaResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result[]> ProductCategoryListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategoryDatos", ReplyAction="http://tempuri.org/IService1/ProductCategoryDatosResponse")]
        clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result ProductCategoryDatos(int ProductCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategoryDatos", ReplyAction="http://tempuri.org/IService1/ProductCategoryDatosResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result> ProductCategoryDatosAsync(int ProductCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategorySave", ReplyAction="http://tempuri.org/IService1/ProductCategorySaveResponse")]
        clientes_wfc.ServiceReference1.stpr_ProductCategorySave_Result ProductCategorySave(int ProductCategoryId, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductCategorySave", ReplyAction="http://tempuri.org/IService1/ProductCategorySaveResponse")]
        System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategorySave_Result> ProductCategorySaveAsync(int ProductCategoryId, string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : clientes_wfc.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<clientes_wfc.ServiceReference1.IService1>, clientes_wfc.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public clientes_wfc.ServiceReference1.stpr_DepartmentList_Result[] DepartmentLista() {
            return base.Channel.DepartmentLista();
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentList_Result[]> DepartmentListaAsync() {
            return base.Channel.DepartmentListaAsync();
        }
        
        public clientes_wfc.ServiceReference1.stpr_DepartmentList_Result DepartmentDatos(int DepartmentID) {
            return base.Channel.DepartmentDatos(DepartmentID);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentList_Result> DepartmentDatosAsync(int DepartmentID) {
            return base.Channel.DepartmentDatosAsync(DepartmentID);
        }
        
        public clientes_wfc.ServiceReference1.stpr_DepartmentSave_Result DepartmentSave(int DepartmentID, string Name, string GroupName) {
            return base.Channel.DepartmentSave(DepartmentID, Name, GroupName);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_DepartmentSave_Result> DepartmentSaveAsync(int DepartmentID, string Name, string GroupName) {
            return base.Channel.DepartmentSaveAsync(DepartmentID, Name, GroupName);
        }
        
        public clientes_wfc.ServiceReference1.stpr_CreditCardList_Result[] CreditCardLista() {
            return base.Channel.CreditCardLista();
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardList_Result[]> CreditCardListaAsync() {
            return base.Channel.CreditCardListaAsync();
        }
        
        public clientes_wfc.ServiceReference1.stpr_CreditCardList_Result CreditCardDatos(int creditCardId) {
            return base.Channel.CreditCardDatos(creditCardId);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardList_Result> CreditCardDatosAsync(int creditCardId) {
            return base.Channel.CreditCardDatosAsync(creditCardId);
        }
        
        public clientes_wfc.ServiceReference1.stpr_CreditCardSave_Result CreditCardSave(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear) {
            return base.Channel.CreditCardSave(CreditCardId, CardType, CardNumber, ExpMonth, ExpYear);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_CreditCardSave_Result> CreditCardSaveAsync(int CreditCardId, string CardType, string CardNumber, int ExpMonth, int ExpYear) {
            return base.Channel.CreditCardSaveAsync(CreditCardId, CardType, CardNumber, ExpMonth, ExpYear);
        }
        
        public clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result[] ProductCategoryLista() {
            return base.Channel.ProductCategoryLista();
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result[]> ProductCategoryListaAsync() {
            return base.Channel.ProductCategoryListaAsync();
        }
        
        public clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result ProductCategoryDatos(int ProductCategoryId) {
            return base.Channel.ProductCategoryDatos(ProductCategoryId);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategoryList_Result> ProductCategoryDatosAsync(int ProductCategoryId) {
            return base.Channel.ProductCategoryDatosAsync(ProductCategoryId);
        }
        
        public clientes_wfc.ServiceReference1.stpr_ProductCategorySave_Result ProductCategorySave(int ProductCategoryId, string Name) {
            return base.Channel.ProductCategorySave(ProductCategoryId, Name);
        }
        
        public System.Threading.Tasks.Task<clientes_wfc.ServiceReference1.stpr_ProductCategorySave_Result> ProductCategorySaveAsync(int ProductCategoryId, string Name) {
            return base.Channel.ProductCategorySaveAsync(ProductCategoryId, Name);
        }
    }
}
